import {
  Patient,
  Gender,
  BloodGroup,
  AppointmentStatus,
  SeverityLevel,
} from "@/types/patient.types";


export const mockPatients: Patient[] = [
  {
    id: "P-001",
    name: "Amit Sharma",
    age: 34,
    gender: Gender.MALE,
    bloodGroup: BloodGroup.B_POS,
    avatar: "https://i.pravatar.cc/150?img=3",

    contact: {
      phone: "9876543210",
      email: "amit.sharma@example.com",
      address: "MG Road",
      city: "Delhi",
      country: "India",
    },

    medicalHistory: [
      {
        id: "M-1",
        condition: "Hypertension",
        diagnosisDate: "2022-05-12",
        severity: SeverityLevel.MEDIUM,
        notes: "Requires regular monitoring",
      },
    ],

    prescriptions: [
      {
        id: "PR-1",
        medication: "Amlodipine",
        dosage: "5mg",
        frequency: "Once daily",
        startDate: "2023-01-01",
      },
    ],

    appointments: [
      {
        id: "A-1",
        date: "2024-03-10",
        doctor: "Dr. Mehta",
        department: "Cardiology",
        status: AppointmentStatus.COMPLETED,
      },
      {
        id: "A-2",
        date: "2024-06-15",
        doctor: "Dr. Mehta",
        department: "Cardiology",
        status: AppointmentStatus.SCHEDULED,
      },
    ],

    vitals: {
      heartRate: 78,
      bloodPressure: "130/85",
      temperature: 98.4,
      oxygenLevel: 97,
    },

    lastVisit: "2024-03-10",
    createdAt: "2022-01-01",
  },

  {
    id: "P-002",
    name: "Priya Verma",
    age: 28,
    gender: Gender.FEMALE,
    bloodGroup: BloodGroup.O_POS,
    avatar: "https://i.pravatar.cc/150?img=5",

    contact: {
      phone: "9123456780",
      email: "priya.verma@example.com",
      address: "Sector 62",
      city: "Noida",
      country: "India",
    },

    medicalHistory: [
      {
        id: "M-2",
        condition: "Diabetes",
        diagnosisDate: "2021-08-20",
        severity: SeverityLevel.HIGH,
        notes: "On insulin therapy",
      },
    ],

    prescriptions: [
      {
        id: "PR-2",
        medication: "Insulin",
        dosage: "10 units",
        frequency: "Twice daily",
        startDate: "2021-09-01",
      },
    ],

    appointments: [
      {
        id: "A-3",
        date: "2024-02-11",
        doctor: "Dr. Singh",
        department: "Endocrinology",
        status: AppointmentStatus.COMPLETED,
      },
    ],

    vitals: {
      heartRate: 82,
      bloodPressure: "120/80",
      temperature: 98.6,
      oxygenLevel: 98,
    },

    lastVisit: "2024-02-11",
    createdAt: "2021-07-10",
  },
  {
  id: "P-003",
  name: "Rahul Mehta",
  age: 45,
  gender: Gender.MALE,
  bloodGroup: BloodGroup.A_POS,
  avatar: "https://i.pravatar.cc/150?img=8",
  contact: {
    phone: "9001112233",
    email: "rahul.mehta@example.com",
    address: "Andheri West",
    city: "Mumbai",
    country: "India",
  },
  medicalHistory: [
    {
      id: "M-3",
      condition: "Coronary Artery Disease",
      diagnosisDate: "2020-03-12",
      severity: SeverityLevel.HIGH,
      notes: "Underwent stent placement",
    },
  ],
  prescriptions: [
    {
      id: "PR-3",
      medication: "Aspirin",
      dosage: "75mg",
      frequency: "Once daily",
      startDate: "2020-04-01",
    },
  ],
  appointments: [
    {
      id: "A-4",
      date: "2024-04-01",
      doctor: "Dr. Shah",
      department: "Cardiology",
      status: AppointmentStatus.COMPLETED,
    },
  ],
  vitals: {
    heartRate: 76,
    bloodPressure: "135/90",
    temperature: 98.2,
    oxygenLevel: 96,
  },
  lastVisit: "2024-04-01",
  createdAt: "2020-02-01",
},

{
  id: "P-004",
  name: "Sneha Kapoor",
  age: 32,
  gender: Gender.FEMALE,
  bloodGroup: BloodGroup.AB_POS,
  avatar: "https://i.pravatar.cc/150?img=9",
  contact: {
    phone: "9812345678",
    email: "sneha.kapoor@example.com",
    address: "Salt Lake",
    city: "Kolkata",
    country: "India",
  },
  medicalHistory: [],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 72,
    bloodPressure: "118/78",
    temperature: 98.5,
    oxygenLevel: 99,
  },
  lastVisit: "2024-01-10",
  createdAt: "2023-05-01",
},

{
  id: "P-005",
  name: "Arjun Reddy",
  age: 38,
  gender: Gender.MALE,
  bloodGroup: BloodGroup.O_NEG,
  avatar: "https://i.pravatar.cc/150?img=12",
  contact: {
    phone: "9012345678",
    email: "arjun.reddy@example.com",
    address: "Banjara Hills",
    city: "Hyderabad",
    country: "India",
  },
  medicalHistory: [
    {
      id: "M-5",
      condition: "Asthma",
      diagnosisDate: "2018-11-11",
      severity: SeverityLevel.MEDIUM,
      notes: "Seasonal flare-ups",
    },
  ],
  prescriptions: [
    {
      id: "PR-5",
      medication: "Inhaler",
      dosage: "2 puffs",
      frequency: "As needed",
      startDate: "2019-01-01",
    },
  ],
  appointments: [],
  vitals: {
    heartRate: 80,
    bloodPressure: "125/82",
    temperature: 98.6,
    oxygenLevel: 95,
  },
  lastVisit: "2024-02-20",
  createdAt: "2018-01-01",
},

{
  id: "P-006",
  name: "Neha Gupta",
  age: 26,
  gender: Gender.FEMALE,
  bloodGroup: BloodGroup.B_NEG,
  avatar: "https://i.pravatar.cc/150?img=15",
  contact: {
    phone: "9998887776",
    email: "neha.gupta@example.com",
    address: "Civil Lines",
    city: "Jaipur",
    country: "India",
  },
  medicalHistory: [],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 70,
    bloodPressure: "110/70",
    temperature: 98.4,
    oxygenLevel: 99,
  },
  lastVisit: "2024-01-05",
  createdAt: "2024-01-01",
},

{
  id: "P-007",
  name: "Vikram Singh",
  age: 52,
  gender: Gender.MALE,
  bloodGroup: BloodGroup.A_NEG,
  avatar: "https://i.pravatar.cc/150?img=20",
  contact: {
    phone: "8887776665",
    email: "vikram.singh@example.com",
    address: "Sector 17",
    city: "Chandigarh",
    country: "India",
  },
  medicalHistory: [
    {
      id: "M-7",
      condition: "Arthritis",
      diagnosisDate: "2019-06-01",
      severity: SeverityLevel.MEDIUM,
      notes: "Joint stiffness",
    },
  ],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 74,
    bloodPressure: "128/85",
    temperature: 98.7,
    oxygenLevel: 97,
  },
  lastVisit: "2024-03-02",
  createdAt: "2019-01-01",
},

{
  id: "P-008",
  name: "Anjali Nair",
  age: 30,
  gender: Gender.FEMALE,
  bloodGroup: BloodGroup.O_POS,
  avatar: "https://i.pravatar.cc/150?img=23",
  contact: {
    phone: "7776665554",
    email: "anjali.nair@example.com",
    address: "MG Road",
    city: "Bangalore",
    country: "India",
  },
  medicalHistory: [],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 72,
    bloodPressure: "115/75",
    temperature: 98.3,
    oxygenLevel: 99,
  },
  lastVisit: "2024-04-02",
  createdAt: "2023-02-01",
},

{
  id: "P-009",
  name: "Karan Malhotra",
  age: 41,
  gender: Gender.MALE,
  bloodGroup: BloodGroup.B_POS,
  avatar: "https://i.pravatar.cc/150?img=25",
  contact: {
    phone: "6665554443",
    email: "karan.malhotra@example.com",
    address: "Connaught Place",
    city: "Delhi",
    country: "India",
  },
  medicalHistory: [
    {
      id: "M-9",
      condition: "Obesity",
      diagnosisDate: "2022-01-01",
      severity: SeverityLevel.HIGH,
      notes: "Diet control required",
    },
  ],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 85,
    bloodPressure: "140/95",
    temperature: 98.8,
    oxygenLevel: 96,
  },
  lastVisit: "2024-04-10",
  createdAt: "2022-01-01",
},

{
  id: "P-010",
  name: "Riya Sen",
  age: 27,
  gender: Gender.FEMALE,
  bloodGroup: BloodGroup.A_POS,
  avatar: "https://i.pravatar.cc/150?img=30",
  contact: {
    phone: "5554443332",
    email: "riya.sen@example.com",
    address: "Park Street",
    city: "Kolkata",
    country: "India",
  },
  medicalHistory: [],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 68,
    bloodPressure: "112/70",
    temperature: 98.2,
    oxygenLevel: 99,
  },
  lastVisit: "2024-03-15",
  createdAt: "2023-06-01",
},

{
  id: "P-011",
  name: "Aditya Roy",
  age: 36,
  gender: Gender.MALE,
  bloodGroup: BloodGroup.AB_NEG,
  avatar: "https://i.pravatar.cc/150?img=33",
  contact: {
    phone: "4443332221",
    email: "aditya.roy@example.com",
    address: "BTM Layout",
    city: "Bangalore",
    country: "India",
  },
  medicalHistory: [],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 75,
    bloodPressure: "122/80",
    temperature: 98.5,
    oxygenLevel: 98,
  },
  lastVisit: "2024-02-28",
  createdAt: "2022-05-01",
},

{
  id: "P-012",
  name: "Pooja Das",
  age: 29,
  gender: Gender.FEMALE,
  bloodGroup: BloodGroup.O_NEG,
  avatar: "https://i.pravatar.cc/150?img=36",
  contact: {
    phone: "3332221110",
    email: "pooja.das@example.com",
    address: "Salt Lake",
    city: "Kolkata",
    country: "India",
  },
  medicalHistory: [],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 70,
    bloodPressure: "110/68",
    temperature: 98.3,
    oxygenLevel: 99,
  },
  lastVisit: "2024-01-20",
  createdAt: "2023-07-01",
},

{
  id: "P-013",
  name: "Rohit Kumar",
  age: 50,
  gender: Gender.MALE,
  bloodGroup: BloodGroup.B_POS,
  avatar: "https://i.pravatar.cc/150?img=40",
  contact: {
    phone: "2221110009",
    email: "rohit.kumar@example.com",
    address: "Patna City",
    city: "Patna",
    country: "India",
  },
  medicalHistory: [
    {
      id: "M-13",
      condition: "Kidney Disease",
      diagnosisDate: "2021-09-01",
      severity: SeverityLevel.HIGH,
      notes: "Dialysis ongoing",
    },
  ],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 88,
    bloodPressure: "150/100",
    temperature: 99,
    oxygenLevel: 94,
  },
  lastVisit: "2024-04-05",
  createdAt: "2021-01-01",
},

{
  id: "P-014",
  name: "Meera Iyer",
  age: 33,
  gender: Gender.FEMALE,
  bloodGroup: BloodGroup.AB_POS,
  avatar: "https://i.pravatar.cc/150?img=44",
  contact: {
    phone: "1110009998",
    email: "meera.iyer@example.com",
    address: "T Nagar",
    city: "Chennai",
    country: "India",
  },
  medicalHistory: [],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 72,
    bloodPressure: "118/76",
    temperature: 98.4,
    oxygenLevel: 99,
  },
  lastVisit: "2024-02-14",
  createdAt: "2023-01-01",
},

{
  id: "P-015",
  name: "Suresh Patel",
  age: 48,
  gender: Gender.MALE,
  bloodGroup: BloodGroup.O_POS,
  avatar: "https://i.pravatar.cc/150?img=47",
  contact: {
    phone: "9990008887",
    email: "suresh.patel@example.com",
    address: "Navrangpura",
    city: "Ahmedabad",
    country: "India",
  },
  medicalHistory: [
    {
      id: "M-15",
      condition: "Diabetes",
      diagnosisDate: "2020-05-01",
      severity: SeverityLevel.MEDIUM,
      notes: "Controlled with medication",
    },
  ],
  prescriptions: [],
  appointments: [],
  vitals: {
    heartRate: 80,
    bloodPressure: "130/85",
    temperature: 98.7,
    oxygenLevel: 97,
  },
  lastVisit: "2024-03-25",
  createdAt: "2020-01-01",
},
];